##
## Build with Travis.CI
##
language: r
cache: packages
sudo: false
# I very much hate doing warnings_are_errors: false, but:
# If I don't do it, I get: 'Warning message: no DISPLAY variable so Tk is not available'
warnings_are_errors: false
#
r:
  - oldrel
  - release
  - devel
jobs:
  include:
    - stage: deploy
      script:
        - |
          R -e 'if(require("aitoaEvaluate")) { remove.packages("aitoaEvaluate"); }; r <- devtools::install_github("thomasWeise/aitoaEvaluate"); if(r == "aitoaEvaluate") { cat("OK\n"); q(save="no", status=0); } else { cat("error: ", r, "\n", sep="", collapse=""); q(save="no", status=1); }'

